### PR TITLE
feat: add nix support(#80)

### PR DESCRIPTION
**Pull request by ICE-GB**
Thanks to (#80) for the example, I did some nix related work, but I have no experience in doing that before this, this pr is still not perfect, I hope someone who is really familiar with nix and rust will help to improve it!

### CODE REVIEW

**Comment by feschber** [comment]
I will read up on nix packaging a bit. And the cachix token should probably be stored in a secret.

**Comment by feschber** [comment]
@ICE-GB @PedroHLC can you give me an update on this? Is this PR still relevant if its in the main nix repos?

Sorry I could not get back to this any sooner

**Comment by PedroHLC** [comment]
Hi @feschber, having a `flake.nix` is worth if the project has several pre-releases tags (we avoid those in nixpkgs) or has a very active development that we cannot follow because of the bureaucracy of reviewing and delays between Hydra deployment cycles. If you believe that's not the case, you can totally skip it (and close this).

Presently, with nix installed in any distro, one can run `nix run nixpkgs#lan-mouse` and use a pre-compiled lan-mouse v0.6.0. Meanwhile, with the `flake.nix` here, one can `nix run 'github:feschber/lan-mouse`, this will (1) fetch latest artifacts from cachix, (2) or if it is missing, automatically, clone the repo (in its latest commit), download all dependencies, build it, and run it. As long as the `flake.nix`'s `packages` is up-to-date with the dependencies list.

**Comment by feschber** [comment]
@ICE-GB I dont have access to the settings for the cache. Can you give me the permissions to generate an access token?

**Comment by ICE-GB** [comment]
> @ICE-GB I dont have access to the settings for the cache. Can you give me the permissions to generate an access token?

Please let me know your cachix account and I'll transfer the permissions to you

**Comment by feschber** [comment]
I signed up via GitHub so same email as on my profile.

**Comment by feschber** [comment]
If that does not work I will create an account

**Comment by ICE-GB** [comment]
> I signed up via GitHub so same email as on my profile.

Now you should have permission to try

**Comment by ICE-GB** [comment]
And I'm trying to transfer the cache to you.

**Comment by feschber** [comment]
It still gives me a 401 on the settings page (https://app.cachix.org/cache/lan-mouse/settings/authtokens)

**Comment by ICE-GB** [comment]
I just deleted it. You can create a new one.

**Comment by feschber** [comment]
Looks like it worked, I reran the build job

**Pull request merged**
