### PR TITLE
Add link to Synergy (open source)

### PR DESCRIPTION
**Pull request by nbolton**
Hey @feschber, I admire and respect the work you're doing with Lan Mouse. It's a great project. As a nod to the potential collaboration between our projects, perhaps you could mention [Synergy 1 Community Edition](https://github.com/symless/synergy) (the original ancestor of the Input Leap fork) which is still in development (as it's the open source core of Synergy 3). I am happy to reciprocate a link to Lan Mouse in the Synergy readme.

### CODE REVIEW

**Comment by feschber** [comment]
Hey @nbolton! I feel honored to get recognition by the pioneers in this area ;). Will do

**Comment by nbolton** [comment]
Sounds like the start of something great. I'll add a link to Lan Mouse in the Synergy readme. For context, I'm thinking of explaining that the projects have different goals much like you do on your readme, and I believe that it'd be good to explore what those are so I don't misrepresent them. If you're open to it, how would be best for us to discuss this? We can discuss it here or somewhere else if you prefer.

**Comment by feschber** [comment]
Thank you I appreciate the advertisement!

We can discuss here or you can message me via the email address in my profile if you prefer.

In the short term the main goal is of course encryption (#104) and support for single direction control (#164) which I'm currently working on.

Aside from that I'm planning to improve platform support and eventually support Android as well.
 
I think it would be cool to have interop with synergy / barrier as well but I have not yet looked at the protocol and how easy that would be to integrate with the existing architecture.
 
The app is also architected in a way that allows to add native frontends for QT / KDE, Windows and MacOS in the future which is something I wanted to approach once the more pressing issues are resolved.

I also want to work on some testing and benchmarking tools eventually.

**Comment by nbolton** [comment]
Sounds good, I'm looking forward to seeing the testing and benchmarking tools, as this is something I've wanted to do with Synergy for a long time but had to prioritise other things.

We have a [very long-term roadmap/vision](https://symless.com/synergy/roadmap) if that's of interest to you. A lot of it will need to be in Synergy 1 (open source) for the proprietary version to work, so you'll be able to see the source when we eventually come to implement those features. Long term, we only plan on having the GUI as the proprietary code (but things can change and who knows, maybe we'll open source everything).

I [added a link to Lan Mouse](https://github.com/symless/synergy/commit/c9eebe0d1a387461dcbbba9f8de1a4403bc1f9e5), but I don't feel like I did what you said justice. I tried to keep it short and sweet as there is way too much text on the README right now but feel free to submit a PR if you want to tweak the wording, as I know that goals can change over time.

**Pull request merged**
